### ISSUE TITLE
[BUG] VMWare Horizon HVD not respecting "Hide the clock when RDP Client or Citrix Workspace are running"

### ISSUE THREAD

**Issue by Bradmeg128** [martinet101/ElevenClock#310]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## Describe the bug
When using VMWare Horizon HVD (for work) the ElevenClock will display over the HVD's native windows taskbar clock.  Its impossible to take a screenshot because the overlay sits on top of the HVD window

## To Reproduce
1. Use VMWare Horizon Client and launch an HVD with full screen, multi-monitor
2. Have ElevenClock running
3. See multiple clocks overlapping in task bar

## Expected behavior
Application should be disabled when in Fullscreen HVD

## Screenshots
Unable to take screenshot

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's v2.5 log: Select all the text and hit Ctrl+C to copy it

---------------------------------------------------------------------------------------------------




en
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
['134,202,255', '95,178,242', '30,145,234', '81,92,107', '69,78,94', '41,47,64', '15,18,36', '239,105,80']
system tray icon disabled
Starting update check
start RDP thread
60.1484375
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Restart loop: 1
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
480
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
['134,202,255', '95,178,242', '30,145,234', '81,92,107', '69,78,94', '41,47,64', '15,18,36', '239,105,80']
[WinError 259] No more data is available

close
close
58.1015625
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-1912, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-3832, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[WinError 259] No more data is available

close
close
59.13671875
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[WinError 259] No more data is available

close
close
59.546875
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Restart loop: 1
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-1912, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-3832, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
[WinError 259] No more data is available

close
close
61.3984375
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(8, 1032, 150, 48)
Full screen rect:  (0, 0, 1920, 1080)
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-1912, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-3832, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
66624 NVIDIA GeForce Overlay (0, 0, 1920, 1080) (0, 0, 1920, 1080)
Restart loop: 1
66624 NVIDIA GeForce Overlay (0, 0, 1920, 1080) (0, 0, 1920, 1080)
66624 NVIDIA GeForce Overlay (0, 0, 1920, 1080) (0, 0, 1920, 1080)
66624 NVIDIA GeForce Overlay (0, 0, 1920, 1080) (0, 0, 1920, 1080)
[WinError 259] No more data is available

close
close
close
61.9140625
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(1762, 1032, 150, 48)
Full screen rect:  (0, 0, 1920, 1080)
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
66624 NVIDIA GeForce Overlay (0, 0, 1920, 1080) (0, 0, 1920, 1080)
66624 NVIDIA GeForce Overlay (0, 0, 1920, 1080) (0, 0, 1920, 1080)
66624 NVIDIA GeForce Overlay (0, 0, 1920, 1080) (0, 0, 1920, 1080)
[WinError 259] No more data is available

close
close
close
62.33984375
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[WinError 259] No more data is available

close
close
62.6796875
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[WinError 259] No more data is available

close
close
63.375
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[WinError 259] No more data is available

close
close
63.65234375
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[WinError 259] No more data is available

close
close
63.921875
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[WinError 259] No more data is available

close
close
64.44921875
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[WinError 259] No more data is available

close
close
64.68359375
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[WinError 259] No more data is available

close
close
64.8828125
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
Restart loop: 1
start RDP thread
[WinError 259] No more data is available
string index out of range
[WinError 259] No more data is available

close
close
65.05078125
<PySide2.QtGui.QScreen(0x170f6939c30, name="\\\\.\\DISPLAY3") at 0x00000170F7174880> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x170f6939d70, name="\\\\.\\DISPLAY1") at 0x00000170F9AC7940> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-158, 1032, 150, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x170f6939fd0, name="\\\\.\\DISPLAY2") at 0x00000170F9AC79C0> PySide2.QtCore.QRect(-3840, 0, 1920, 1080) (1920, 1080, -3840, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2078, 1032, 150, 48)
Full screen rect:  (-3840, 0, -1920, 1080)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1

```

**Comment by martinet101** [comment]
what is the process name of VMWare Horizon HVD

**Comment by Bradmeg128** [comment]
VMware Horizon Client 32-Bit (32 bit)

**Comment by martinet101** [comment]
I need you to find the process name, to do that:
1. open task manager
2. Click on "More details"
3. Go to Details tab
4. Find your app name in description.
5. Send me the process name:
![image](https://user-images.githubusercontent.com/53119851/142902659-afd0dcce-532f-4336-a81c-a68e3466592c.png)

**Comment by Bradmeg128** [comment]
Unclear as to which vmware process it is 100% but my guess is its likely vmware-view.exe
***@***.***

**Comment by martinet101** [comment]
You are not running the lastest version due to ssl errors. Try updating and see what happens.

**Comment by Bradmeg128** [comment]
Just updated to 2.7, now I have a different issue. ElevenClock shows running in task bar but its not opening on the desktop, its not on any task bar and I cant click on anything to bring up its settings.

I have tried a full uninstall and reinstall, same issue

**Comment by martinet101** [comment]
can you send me please your log?

**Comment by Bradmeg128** [comment]
---------------------------------------------------------------------------------------------------

ElevenClock's 2.7.0 (v2.7) log: Select all the text and hit Ctrl+C to copy it
All modules loaded successfully and sys.stdout patched correctly, starting main script
Translator function set language to "en"

---------------------------------------------------------------------------------------------------




system tray icon disabled
Starting update check
start RDP thread
62.140625
<PySide2.QtGui.QScreen(0x1fe463c98a0, name="\\\\.\\DISPLAY3") at 0x000001FE46DC6E80> (1920, 1080, 0, 0, 96.0, [(<PyHANDLE:65539>, <PyHANDLE:0>, (-1920, 0, 0, 1080)), (<PyHANDLE:65541>, <PyHANDLE:0>, (-3840, 0, -1920, 1080)), (<PyHANDLE:309332539>, <PyHANDLE:0>, (0, 0, 1920, 1080))])
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x1fe463c9360, name="\\\\.\\DISPLAY1") at 0x000001FE46DDD4C0> (1920, 1080, -1920, 0, 96.0, [(<PyHANDLE:65539>, <PyHANDLE:0>, (-1920, 0, 0, 1080)), (<PyHANDLE:65541>, <PyHANDLE:0>, (-3840, 0, -1920, 1080)), (<PyHANDLE:309332539>, <PyHANDLE:0>, (0, 0, 1920, 1080))])
Regular sized taskbar
(-1920, 0, 0, 1080)
PySide2.QtCore.QRect(-1920, 0, 1920, 1080)
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-200, 1032, 200, 48)
Font families: ['Segoe UI Variable Display', 'sans-serif']
Font size: 9.3
Full screen rect: (-1920, 0, 0, 1080)
Show or hide loop started with following parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:True, ClockOn1Mon:False, NefWSMethod:False
<PySide2.QtGui.QScreen(0x1fe463c9560, name="\\\\.\\DISPLAY2") at 0x000001FE46DDD6C0> (1920, 1080, -3840, 0, 96.0, [(<PyHANDLE:65539>, <PyHANDLE:0>, (-1920, 0, 0, 1080)), (<PyHANDLE:65541>, <PyHANDLE:0>, (-3840, 0, -1920, 1080)), (<PyHANDLE:309332539>, <PyHANDLE:0>, (0, 0, 1920, 1080))])
Regular sized taskbar
(-3840, 0, -1920, 1080)
PySide2.QtCore.QRect(-3840, 0, 1920, 1080)
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-2120, 1032, 200, 48)
Font families: ['Segoe UI Variable Display', 'sans-serif']
Font size: 9.3
Full screen rect: (-3840, 0, -1920, 1080)
Show or hide loop started with following parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:True, ClockOn1Mon:False, NefWSMethod:False
Restart loop: 1
Traceback (most recent call last):

File "urllib\request.py", line 1346, in do_open

File "http\client.py", line 1285, in request

File "http\client.py", line 1331, in _send_request

File "http\client.py", line 1280, in endheaders

File "http\client.py", line 1040, in _send_output

File "http\client.py", line 980, in send

File "http\client.py", line 1454, in connect

File "ssl.py", line 500, in wrap_socket

File "ssl.py", line 1040, in _create

File "ssl.py", line 1309, in do_handshake

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 91, in updateIfPossible

File "urllib\request.py", line 214, in urlopen

File "urllib\request.py", line 517, in open

File "urllib\request.py", line 534, in _open

File "urllib\request.py", line 494, in _call_chain

File "urllib\request.py", line 1389, in https_open

File "urllib\request.py", line 1349, in do_open

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>)
Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
updates not found

**Comment by Bradmeg128** [comment]
I think I see the ‘issue’

You made it work with Horizon HVD, and whenever I launch that it removes the extra clocks.  It just also removes them even if I have that HVD minimized or if it is running on a different virtual desktop.  So if I alt-tab or minimize my HVD client, the clocks are still missing until I actually close the client.

This works to stop the issue, but means ElevenClock won’t work while I have any HVD open in any desktop.  Not ideal but its workable ☺

**Comment by martinet101** [comment]
Then could you try disabling "Hode on RDP and Cytrix" and enabling "Hide on multi-monitor fullscreen apps"?

**Comment by Bradmeg128** [comment]
That works!

One last thing, I have automatic updates checked, any idea why it didn’t automatically update from 2.5 to 2.7?

**Comment by martinet101** [comment]
Yes, i had ssl errors, but on 2.6 a fix was implemented. It should now update as usual
