### ISSUE TITLE
[BUG] YouTube and other full screen video controls appear under elevenclock when using full screen. 

### ISSUE THREAD

**Issue by Erag0rn** [martinet101/ElevenClock#347]
## Describe the bug
See screenshot below. When watching a youtube, twitch or another video full screen, elevenclock appears above the video controls so you can't escape or click other buttons. I have a 3 monitor setup if that matters. 

## To Reproduce
not needed

## Screenshots
 https://imgur.com/a/ND3GMP1

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

---------------------------------------------------------------------------------------------------

   ElevenClock's 2.8.0 (v2.8) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🟦: Information
 🟩: Task completed successfully
 🟨: Expected warning
 🟧: Unexpected warning
 🟥: Error

🟦 System tray icon enabled
🟦 Starting update check
🟨 This is primay screen and is set to be skipped
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(2560, -4, 2560, 1440)
🟩 Taskbar at bottom
🟨 Clock on the left
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(4920, 1388, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 10.5
🟩 Using white text (dark mode)
🟦 Full screen rect:  (2560, -4, 5120, 1436)
🟦 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(1298, -1444, 2560, 1440)
🟩 Taskbar at bottom
🟨 Clock on the left
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(3658, -52, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 10.5
🟩 Using white text (dark mode)
🟦 Full screen rect:  (1298, -1444, 3858, -4)
🟦 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟦 Restart loop: 1
🟥 Traceback (most recent call last):

🟥   File "urllib\request.py", line 1346, in do_open

🟥   File "http\client.py", line 1285, in request

🟥   File "http\client.py", line 1331, in _send_request

🟥   File "http\client.py", line 1280, in endheaders

🟥   File "http\client.py", line 1040, in _send_output

🟥   File "http\client.py", line 980, in send

🟥   File "http\client.py", line 1454, in connect

🟥   File "ssl.py", line 500, in wrap_socket

🟥   File "ssl.py", line 1040, in _create

🟥   File "ssl.py", line 1309, in do_handshake

🟥 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

🟥 
During handling of the above exception, another exception occurred:


🟥 Traceback (most recent call last):

🟥   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 95, in updateIfPossible

🟥   File "urllib\request.py", line 214, in urlopen

🟥   File "urllib\request.py", line 517, in open

🟥   File "urllib\request.py", line 534, in _open

🟥   File "urllib\request.py", line 494, in _call_chain

🟥   File "urllib\request.py", line 1389, in https_open

🟥   File "urllib\request.py", line 1349, in do_open

🟥 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

🟥 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>)
🟦 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟩 Updates not found
🟨 Fullscreen window detected! Emongg - Twitch - Google Chrome (2560, -4, 5120, 1436) Fullscreen rect: (2560, -4, 5120, 1436)
🟨 Fullscreen window detected! Emongg - Twitch - Google Chrome (2560, -4, 5120, 1436) Fullscreen rect: (2560, -4, 5120, 1436)
🟨 Fullscreen window detected! Emongg - Twitch - Google Chrome (2560, -4, 5120, 1436) Fullscreen rect: (2560, -4, 5120, 1436)
🟨 Fullscreen window detected! Emongg - Twitch - Google Chrome (2560, -4, 5120, 1436) Fullscreen rect: (2560, -4, 5120, 1436)
🟨 Fullscreen window detected! Emongg - Twitch - Google Chrome (2560, -4, 5120, 1436) Fullscreen rect: (2560, -4, 5120, 1436)
🟨 Fullscreen window detected! Emongg - Twitch - Google Chrome (2560, -4, 5120, 1436) Fullscreen rect: (2560, -4, 5120, 1436)
🟨 Fullscreen window detected! Emongg - Twitch - Google Chrome (2560, -4, 5120, 1436) Fullscreen rect: (2560, -4, 5120, 1436)
🟨 Fullscreen window detected! Emongg - Twitch - Google Chrome (2560, -4, 5120, 1436) Fullscreen rect: (2560, -4, 5120, 1436)
🟨 Fullscreen window detected! Emongg - Twitch - Google Chrome (2560, -4, 5120, 1436) Fullscreen rect: (2560, -4, 5120, 1436)
🟨 Fullscreen window detected! Emongg - Twitch - Google Chrome (2560, -4, 5120, 1436) Fullscreen rect: (2560, -4, 5120, 1436)


If the issue can be reproduced (As an example: After waiting 5 mintues, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by Masamune3210** [comment]
There is a option to disable showing over fullscreen apps in the settings

**Comment by martinet101** [comment]
@Erag0rn, what @Masamune3210 said is right. If you take a look OK your log, it actually detects the window, but it does not hide because the mode is not enabled

**Comment by alexejk** [comment]
The likely source of the issue is that when you install the app, the option is ticked by default in settings but is not applied. Untick and re-tick leads to it working properly and not its hidden! But i assume "defaults" don't match :)

**Comment by martinet101** [comment]
Mhmm, i'll take a look

**Comment by martinet101** [comment]
Yes, found the issue, it was an old settings migrator.

**Comment by martinet101** [comment]
Fixed, coming in the next version
