### ISSUE TITLE
[BUG] ElevenClock Features do not Apply

### ISSUE THREAD

**Issue by Spidersouris** [martinet101/ElevenClock#377]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
</b>

## Describe the bug
Sorry about my title not being any clearer but I don't really know what's causing this. I installed this software because I wanted to show seconds in the Windows clock, a feature that I miss a lot since I have upgraded to W11. However, it seems the software doesn't work at all, as the clock is no different from usual and settings do not apply. You'll find the log below.
Thanks!

Windows 11 Build is 22518.rs_prerelease.211203-1458

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 2.9.0 (v2.9) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🔵 System tray icon enabled
🔵 Starting update check
🟡 This is primay screen and is set to be skipped
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1346, in do_open

🔴   File "http\client.py", line 1285, in request

🔴   File "http\client.py", line 1331, in _send_request

🔴   File "http\client.py", line 1280, in endheaders

🔴   File "http\client.py", line 1040, in _send_output

🔴   File "http\client.py", line 980, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 500, in wrap_socket

🔴   File "ssl.py", line 1040, in _create

🔴   File "ssl.py", line 1309, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 95, in updateIfPossible

🔴   File "urllib\request.py", line 214, in urlopen

🔴   File "urllib\request.py", line 517, in open

🔴   File "urllib\request.py", line 534, in _open

🔴   File "urllib\request.py", line 494, in _call_chain

🔴   File "urllib\request.py", line 1389, in https_open

🔴   File "urllib\request.py", line 1349, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>)
🔵 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found

**Comment by martinet101** [comment]
You need to open the settings and then, under Clock settings, enable "Show clock on primary screen". See #333 for more info
