### ISSUE TITLE
DLL load failed error shown

### ISSUE THREAD

**Issue by BMurri** [martinet101/ElevenClock#550]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If the issue is with the bottom cropped text of the clock, this has been fixed and will come with the next release

</b>

## Describe the bug
DLL load failed

## To Reproduce
Steps to reproduce the behaviour:
1. Log in after hibernating
2. Notice dialog box on screen.

- Notice dialog box title mentions 16-bit binaries (this is a 64-bit system)
- Notice dialog text mentions the binary that couldn't be run was "\\??\C:\WINDOWS\system32\cmd.exe"

3. Think to self "this is weird", acknowledge dialog (there's only one button) and then notice browser window is open
4. See error in aforementioned web browser window (with header `SomePythonThings Error Report`)

## Expected behaviour
No errors :)

## Screenshots
```
                        OS: Windows
                   Version: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: Unknown
          APP Version Code: Unknown
                   Program: ElevenClock

-----------------------------------------------------------------------------------------



ElevenClock Log:




Traceback (most recent call last):
  File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 20, in <module>
  File "C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "psutil\__init__.py", line 109, in <module>
  File "C:\Users\marti\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "psutil\_pswindows.py", line 35, in <module>

ImportError: DLL load failed while importing _psutil_windows: %1 is not a valid Win32 application.<class 'ImportError'>: DLL load failed while importing _psutil_windows: %1 is not a valid Win32 application.

```
## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.0 (v3.2) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 3840, 2160)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3590, 2100, 250, 60)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Restart loop: 1
🔵 Full screen rect:  (0, 0, 3840, 2160)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(3840, -907, 2160, 3840)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(5750, 2873, 250, 60)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (3840, -907, 6000, 2933)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 12.34566617012024
🟢 Cached text input host hwnd: 66148
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 22.517165422439575
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/we-are-on-twitter.webp
🟡 Closing clock on {'Monitor': (0, 0, 3840, 2160), 'Work': (0, 0, 3840, 2100), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🟡 Closing clock on {'Monitor': (3840, -907, 6000, 2933), 'Work': (3840, -907, 6000, 2873), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(3840, -907, 2160, 3840)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(5750, 2873, 250, 60)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (3840, -907, 6000, 2933)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Restart loop: 1
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/we-are-on-twitter.webp
🔵 Copying log to the clipboard...
```

## Additional context
I did not screenshot the dialog box. Sorry.
I did send the error report from the web browser.

**Comment by martinet101** [comment]
I see... there might be some kind of error while importing psutil... I'll add an exception checker on this piece of code

**Comment by martinet101** [comment]
Fixed, coming with the next release
