### ISSUE TITLE
[BUG] FONT ISSUES

### ISSUE THREAD

**Issue by martinet101** [martinet101/ElevenClock#590]
Issues with fonts in the clock on version 3.2.1

Please all post here

**Comment by BloodEnix** [comment]
Bug for russian font. After update 3.2.1.
![Screenshot_55](https://user-images.githubusercontent.com/99691395/153948722-00aac605-8e53-4745-86d4-1579a2596778.png)

**Comment by erbinr** [comment]
Seems to have encoding problems with this version and locale (not happening previous update)

![image](https://user-images.githubusercontent.com/28494221/153955750-b19b07d8-5425-431a-ba99-d5ba87fcc336.png)
![image](https://user-images.githubusercontent.com/28494221/153955856-06a3b607-01bf-4954-b936-0766d2900f06.png)

**Comment by kslifter** [comment]
Mine is crashing shortly after opening as well. 

Here is my log:
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.1 (v3.21) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟡 Small sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 3840, 2160)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3490, 2104, 350, 56)
🔵 Font families: ['Arial']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟡 Small sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-3840, 0, 3840, 2160)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-350, 2104, 350, 56)
🔵 Font families: ['Arial']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (-3840, 0, 0, 2160)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 0.7065572738647461
🔵 Restart loop: 1
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.4960269927978516
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/error.webp
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔵 Copying log to the clipboard...

**Comment by King-May** [comment]
AM/PM error in Traditional Chinese
![未命名](https://user-images.githubusercontent.com/19802126/153969260-444d5509-38b5-4b0c-b6aa-e49f2ded8d4e.png)

**Comment by urtbest86** [comment]
Me too. AM/PM error in Korean and English.
![image](https://user-images.githubusercontent.com/56027961/153971208-d1fa8526-d540-4b85-aca9-e894e4258528.png)
![image](https://user-images.githubusercontent.com/56027961/153971260-43af88f4-7706-4d84-8e33-3e31d519e4b6.png)

**Comment by portgasdpetch** [comment]
sometimes, I can not click the clock to show the calendar(the calendar and notification will not show up). Always happen when I use 'find function (ctrl+F)' on a web browser in my language(only in Thai language, not English), also happen by other causes. I have to use 'windows search(windows + s)' or find function on a web browser in English to make the clock work(to be clicked and show the calendar) again. Also the clock font is weird, like it is not in English language(you can see the Tue back to normal form while I was using windows search).
ps. I pressed enter every time I used 'find function' on web browser

https://user-images.githubusercontent.com/23282812/153995451-85b7a632-8b60-4619-b000-810d5fc60447.mp4


https://user-images.githubusercontent.com/23282812/153995459-aa494741-2161-4176-aaa8-8d813a8502c5.mp4

**Comment by portgasdpetch** [comment]
sorry

**Comment by daswareinfach** [comment]
same here. 
![image](https://user-images.githubusercontent.com/35432275/154054251-2f96d8f2-8101-4d3d-90b8-ea717844a067.png)

![image](https://user-images.githubusercontent.com/35432275/154054231-7d64c174-2511-49b3-a468-2758a4ee3fe4.png)

**Comment by lanthimosg** [comment]
Also wrong characters on Greek Language.

**Comment by ad2k22** [comment]
![image](https://user-images.githubusercontent.com/98554913/154090715-0d2387de-a91d-4da4-8006-f8fbc7c16fc1.png)
Also Russian language.

**Comment by martinet101** [comment]
I have good news! the latest head has a solution for the issue, and an urgent update will be released asap!

**Comment by martinet101** [comment]
Update to the latest version, it should now work

**Comment by vladimir-kordas** [comment]
(3.2.2) Problem with formatting numbers that end in 1. When a value ends in 1, it shifts the whole time to that moment (as if there is a blank space after the 1). I am attaching a sample video.

https://user-images.githubusercontent.com/81954797/154139507-5796e894-b773-4187-9f71-ce6e1195b48e.mp4

**Comment by martinet101** [comment]
Which font are you using?

**Comment by vladimir-kordas** [comment]
Calibri Light

**Comment by martinet101** [comment]
Can you try setting the default font?

**Comment by vladimir-kordas** [comment]
By default it does similarly for me at number 2, but really imperceptibly. However, Calibri Light worked beautifully in the previous version.

**Comment by martinet101** [comment]
> Calibri Light worked beautifully in the previous version.

But Segoe UI did not. Gotta add a switch on the settings. 

Is this something urgent ? like could you wait 5-6 days?

**Comment by vladimir-kordas** [comment]
It's okay. It's not an urgent. Thanks for your work 👍

**Comment by martinet101** [comment]
Ok

**Comment by shiawasenahikari** [comment]
In version 3.2.2, when I "show seconds", and use a custom monospace font (e.g. Consolas), when the time reaches xx:xx:x1, the shown time will be shifted to left a little.
![1](https://user-images.githubusercontent.com/32567875/154189788-cc387a24-7689-4b36-88fc-d2b1c005380d.png)

**Comment by martinet101** [comment]
The issue has been fixed and will come with the next release
