### ISSUE TITLE
[BUG] ElevenClock forces an update which immediately crashes

### ISSUE THREAD

**Issue by MeachamusPrime** [martinet101/ElevenClock#601]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the [FAQ](https://github.com/martinet101/ElevenClock/wiki/Troubleshooting) for solutions<br>
✅ I have installed the latest version and the issue still happens<br>
 
# for issues related with font corruption see #590
 
</b>

## Describe the bug
1. When ElevenClock starts it immediately downloads an update.
2. The Update cannot be canceled.
3. Once installed the update crashes ElevenClock every time it runs.
4. ElevenClock must be uninstalled and reinstalled.
5. Go to 1.

## To Reproduce
Steps to reproduce the behaviour:
1. See "Describe the bug"

## Expected behaviour
1. ElevenClock allows you to cancel the upgrade, or
2. ElevenClock does not crash after the upgrade

## Screenshots
N/A

## The Log
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.0 (v3.2) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 2560, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(2360, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 2560, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(782, -2160, 3840, 2160)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(4322, -72, 300, 72)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (782, -2160, 4622, 0)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 2...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-900, -188, 900, 1440)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 1204, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-900, -188, 0, 1252)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 1.435305118560791
🔵 Restart loop: 1
🟢 Cached text input host hwnd: 15077580
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🟣 Expected AttributeError on backgroundLoop thread
🟠 Update checking disabled
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.9616901874542236
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/error.webp
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1346, in do_open

🔴   File "http\client.py", line 1285, in request

🔴   File "http\client.py", line 1331, in _send_request

🔴   File "http\client.py", line 1280, in endheaders

🔴   File "http\client.py", line 1040, in _send_output

🔴   File "http\client.py", line 980, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 500, in wrap_socket

🔴   File "ssl.py", line 1040, in _create

🔴   File "ssl.py", line 1309, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

🔴 
During handling of the above exception, another exception occurred:

🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 124, in updateIfPossible

🔴   File "urllib\request.py", line 214, in urlopen

🔴   File "urllib\request.py", line 517, in open

🔴   File "urllib\request.py", line 534, in _open

🔴   File "urllib\request.py", line 494, in _call_chain

🔴   File "urllib\request.py", line 1389, in https_open

🔴   File "urllib\request.py", line 1349, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>)
🔵 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates found!
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/error.webp
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```
Log after upgrade issue is unavailable due to crash.

## Additional context
I was able to find the setting to disable automatic updates before it updated on the 10th attempt.

**Comment by martinet101** [comment]
In theory, OSError should be captured, so I don't think it might be the cause. I'll take a look.

**Comment by martinet101** [comment]
So,, the update is launched or not? I mean, if you open task manager, it does lanuch some kind of setup.exe/updater.exe/installler.exe?
