### ISSUE TITLE
[BUG] Two clocks appear, overlapping, on primary monitor

### ISSUE THREAD

**Issue by c-eg** [martinet101/ElevenClock#606]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the [FAQ](https://github.com/martinet101/ElevenClock/wiki/Troubleshooting) for solutions<br>
✅ I have installed the latest version and the issue still happens<br>
 
# for issues related with font corruption see #590
 
</b>

## Describe the bug
Eleven Clock overlaps the original windows 11 clock.
![image](https://user-images.githubusercontent.com/68134729/154125901-3838a04c-8f50-4d8b-96c2-2e210d943601.png)

## To Reproduce
Steps to reproduce the behaviour:
When I start windows, it appears. These are the settings I have 
![image](https://user-images.githubusercontent.com/68134729/154126113-a3d2ac72-c801-46a8-88d4-7ccdb0eb6140.png)
Everything else is default.

## Expected behaviour
Not to have a double overlayed clocked.

## Screenshots
Have above

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.1 (v3.21) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 2560, 1440)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(2360, 1392, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d/%m/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:False, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1920, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d/%m/%Y
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:False, legacyFullScreenMethod:False
🟢 Loaded clocks in 1.0142996311187744
🔵 Restart loop: 1
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to True
🟢 Loaded everything in 1.6848511695861816
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d/%m/%Y
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🟡 Closing clock on {'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2560, 1392), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🟡 Closing clock on {'Monitor': (-1920, 0, 0, 1080), 'Work': (-1920, 0, 0, 1032), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 2560, 1440)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(2360, 1392, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d/%m/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:False, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1920, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d/%m/%Y
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:False, legacyFullScreenMethod:False
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d/%m/%Y
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/error.webp
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1112, in paintEvent

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🔵 Copying log to the clipboard...

```

**Comment by martinet101** [comment]
Please do:
1. Update to the latest version
2. Reset elevenclock using the button placed on the settings window, under debugging information

**Comment by c-eg** [comment]
Just updated and reset but still getting the same issue.

**Comment by martinet101** [comment]
Please make sure that the following items are disabled:

![image](https://user-images.githubusercontent.com/53119851/154144985-8e3dbca1-d453-4db3-ad69-5cabb0d7d784.png)

**Comment by c-eg** [comment]
That fixed it! But I would prefer to have the notification badge disabled on both monitors

**Comment by martinet101** [comment]
But the main reason of seeing the original clock under elevenclock is is because the main clock shows the badge, while elevenclock didn't
