### ISSUE TITLE
[BUG] ElevenClock will block by the taskbar, and it will not displays fine.

### ISSUE THREAD

**Issue by chinanoahli** [martinet101/ElevenClock#629]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the [FAQ](https://github.com/martinet101/ElevenClock/wiki/Troubleshooting) for solutions<br>
✅ I have installed the latest version and the issue still happens<br>
 
# for issues related with font corruption see #590
 
</b>

## To Reproduce
Steps to reproduce the behaviour:
1. install and start Eleven Clock
2. ElevenClock will show behind the taskbar(I set my taskbar to auto hide, when the taskbar was hidden, I can see the ElevenClock was behind it.)
3. After several tried(restart the ElevenClock), ElevenClock just not showing anymore.

## Expected behaviour
Well, ElevenClock displays fine?

## Screenshots
Now, ElevenClock was not display any more, so no screenshot here.

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.3 (v3.23) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟡 This is the primary screen and is set to be skipped
🟢 Loaded clocks in 0.19533467292785645
🟠 Unable to parse int from ClockXOffset settings value
🔵 Restart loop: 1
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 0.7755494117736816
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 This is the primary screen and is set to be skipped
🔵 tDateMode: yyyy/M/d
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M:%S·
%Y/%#m/%#d
🔵 Restart loop: 1
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/rose.webp
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
```

## Additional context
I was using win11 20h2 22000.493

**Comment by martinet101** [comment]
Can you try resetting ElevenClock?

**Comment by martinet101** [comment]
Bcause your log shows the main screen clock is ommitted for whatever the reason

**Comment by chinanoahli** [comment]
Seem I found what cause issue:
```
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.3 (v3.23) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "zh_CN"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟡 ElevenClock set to hide with the taskbar
🟡 Taskbar at bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 591, in __init__

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 591, in __init__

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['JetBrains Mono']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/M/d
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M:%S·
%Y/%#m/%#d
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 2.5504820346832275
🟢 Cached text input host hwnd: 131772
🟠 Mouse thread returned AttributeError
🟠 Unable to parse int from ClockXOffset settings value
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 3.048480987548828
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1080), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟡 ElevenClock set to hide with the taskbar
🟡 Taskbar at bottom
🟢 Clock on the right
🟡 X offset being used!
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 591, in __init__

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['JetBrains Mono']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/M/d
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M:%S·
%Y/%#m/%#d
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: yyyy/M/d
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M:%S·
%Y/%#m/%#d
🟢 Cached text input host hwnd: 131772
🔵 Restart loop: 1
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Fullscreen window detected! [BUG] ElevenClock will block by the taskbar, and it will not displays fine. · Issue #629 · martinet101/ElevenClock 和另外 2 个页面 - 用户配置 1 - Microsoft​ Edge (-9, -9, 1929, 1089) Fullscreen rect: (0, 0, 1920, 1080)
🟡 Fullscreen window detected! [BUG] ElevenClock will block by the taskbar, and it will not displays fine. · Issue #629 · martinet101/ElevenClock 和另外 2 个页面 - 用户配置 1 - Microsoft​ Edge (-9, -9, 1929, 1089) Fullscreen rect: (0, 0, 1920, 1080)
🟡 Fullscreen window detected! [BUG] ElevenClock will block by the taskbar, and it will not displays fine. · Issue #629 · martinet101/ElevenClock 和另外 2 个页面 - 用户配置 1 - Microsoft​ Edge (-9, -9, 1929, 1089) Fullscreen rect: (0, 0, 1920, 1080)
🟡 Fullscreen window detected! [BUG] ElevenClock will block by the taskbar, and it will not displays fine. · Issue #629 · martinet101/ElevenClock 和另外 2 个页面 - 用户配置 1 - Microsoft​ Edge (-9, -9, 1929, 1089) Fullscreen rect: (0, 0, 1920, 1080)
🟡 Fullscreen window detected! [BUG] ElevenClock will block by the taskbar, and it will not displays fine. · Issue #629 · martinet101/ElevenClock 和另外 2 个页面 - 用户配置 1 - Microsoft​ Edge (-9, -9, 1929, 1089) Fullscreen rect: (0, 0, 1920, 1080)
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1080), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟡 ElevenClock set to hide with the taskbar
🟡 Taskbar at bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 591, in __init__

🔴 ValueError: invalid literal for int() with base 10: ''

🔴 Note this traceback was caught by reporter and has been added to the log (invalid literal for int() with base 10: '')
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['JetBrains Mono']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/M/d
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M:%S·
%Y/%#m/%#d
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: yyyy/M/d
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M:%S·
%Y/%#m/%#d
```

In my computer, auto hide taskbar, and some maximize windows will been treated as fullscreen windows, so that ElevenClock won't show.

**Comment by chinanoahli** [comment]
But, It looks like some code was wrong:
```
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 591, in __init__

🔴 ValueError: invalid literal for int() with base 10: ''
```
This error keep showing in the log, and the settings not taking effect most time.

After launch the app, sometime it can not work correctly. It has to been reload clock manually.


https://user-images.githubusercontent.com/10005128/155825006-aeb4e35c-81ca-43ab-a352-79210babb18a.mp4

**Comment by martinet101** [comment]
Ok, I see what is happening. Please take in account that the errors shown are not related to the clock not showing (Believeit or not, those were kind of expected), but rather as you said, the fullscreen method detects maximized windows as fullscreen. 

This needs to be fixed

**Comment by martinet101** [comment]
Fixed, cmoing in the next release
