### ISSUE TITLE
[BUG] (Error appears with Japanese language and 'second' indicate)

### ISSUE THREAD

**Issue by sf68060** [martinet101/ElevenClock#652]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ ] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
"Invalid time format Please modify it in the settings"
I'm using this app with Japanese settings and settings with seconds display. Since the app was updated automatically on 3/2 today, the seconds cannot be displayed due to the above error. Even if you reinstall this app with the 1.8 installer, the same phenomenon will occur with automatic update. It works if you turn off the seconds display, but I absolutely need the seconds display.

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "tools.py", line 142, in setSettingsValue

🔴   File "tools.py", line 142, in setSettingsValue

🔴   File "globals.py", line 11, in loadTimeFormat

🔴   File "globals.py", line 11, in loadTimeFormat

🔴 NotImplementedError: loadTimeFormat function has not been defined!

🔴 NotImplementedError: loadTimeFormat function has not been defined!

🔴 Note this traceback was caught by reporter and has been added to the log (loadTimeFormat function has not been defined!)
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.3.0 (v3.3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "ja"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1280, -723, 1280, 1024)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 253, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (-1280, -723, 0, 301)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🟢 Loaded clocks in 0.21500444412231445
🔵 Restart loop: 1
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🟡 Closing clock on {'Monitor': (-1280, -723, 0, 301), 'Work': (-1280, -723, 0, 253), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 3840, 2160)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3640, 2112, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1280, -723, 1280, 1024)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 253, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (-1280, -723, 0, 301)
🔵 Restart loop: 1
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🟡 Closing clock on {'Monitor': (0, 0, 3840, 2160), 'Work': (0, 0, 3840, 2112), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🟡 Closing clock on {'Monitor': (-1280, -723, 0, 301), 'Work': (-1280, -723, 0, 253), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 3840, 2160)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3640, 2112, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1280, -723, 1280, 1024)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 253, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (-1280, -723, 0, 301)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🟢 Cached text input host hwnd: 131590
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🟡 Closing clock on {'Monitor': (0, 0, 3840, 2160), 'Work': (0, 0, 3840, 2112), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🟡 Closing clock on {'Monitor': (-1280, -723, 0, 301), 'Work': (-1280, -723, 0, 253), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 3840, 2160)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3640, 2112, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1280, -723, 1280, 1024)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 253, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (-1280, -723, 0, 301)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🟡 Closing clock on {'Monitor': (0, 0, 3840, 2160), 'Work': (0, 0, 3840, 2112), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🟡 Closing clock on {'Monitor': (-1280, -723, 0, 301), 'Work': (-1280, -723, 0, 253), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 3840, 2160)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3640, 2112, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1280, -723, 1280, 1024)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 253, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (-1280, -723, 0, 301)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🟢 Cached text input host hwnd: 131590
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🟡 Closing clock on {'Monitor': (0, 0, 3840, 2160), 'Work': (0, 0, 3840, 2112), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🟡 Closing clock on {'Monitor': (-1280, -723, 0, 301), 'Work': (-1280, -723, 0, 253), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 3840, 2160)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3640, 2112, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1280, -723, 1280, 1024)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 253, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (-1280, -723, 0, 301)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🟢 Default settings loaded
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🟡 Closing clock on {'Monitor': (0, 0, 3840, 2160), 'Work': (0, 0, 3840, 2112), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🟡 Closing clock on {'Monitor': (-1280, -723, 0, 301), 'Work': (-1280, -723, 0, 253), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 3840, 2160)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3640, 2112, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Restart loop: 5
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1280, -723, 1280, 1024)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 253, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (-1280, -723, 0, 301)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🟢 Loaded everything in 1.1879000663757324
🟢 Cached text input host hwnd: 131590
🔵 Restart loop: 4
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Restart loop: 3
🔵 Restart loop: 2
🔵 Restart loop: 1
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🟡 Closing clock on {'Monitor': (0, 0, 3840, 2160), 'Work': (0, 0, 3840, 2112), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🟡 Closing clock on {'Monitor': (-1280, -723, 0, 301), 'Work': (-1280, -723, 0, 253), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 3840, 2160)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3640, 2112, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1280, -723, 1280, 1024)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 253, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 Full screen rect:  (-1280, -723, 0, 301)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🟢 Cached text input host hwnd: 131590
🔵 Restart loop: 1
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M:%S 
%Y/%m/%d
🟠 Update checking disabled
🔴 Traceback (most recent call last):

🔴   File "\\10.255.255.1\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 410, in timeStrThread

🔴 UnicodeEncodeError: 'locale' codec can't encode character '\u200a' in position 9: encoding error

🔴 Note this traceback was caught by reporter and has been added to the log ('locale' codec can't encode character '\u200a' in position 9: encoding error)
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%Y/%m/%d
🔵 tDateMode: yyyy/MM/dd
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M:%S 
%Y/%m/%d
🔴 Traceback (most recent call last):

🔴   File "\\10.255.255.1\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 410, in timeStrThread

🔴 UnicodeEncodeError: 'locale' codec can't encode character '\u200a' in position 9: encoding error

🔴 Note this traceback was caught by reporter and has been added to the log ('locale' codec can't encode character '\u200a' in position 9: encoding error)
🔵 Copying log to the clipboard...

```

**Comment by sf68060** [comment]
I found another similar old post, so I'll close it.
