### ISSUE TITLE
[BUG/ISSUE] Changing the action done when the clock is clicked

### ISSUE THREAD

**Issue by reZdotjson** [martinet101/ElevenClock#779]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

Always reverts setting to open calendar when clicked instead of the desired action inputted from the drop down menu

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'Clock Settings' in ElevenClock Settings
2. Checkmark the option which says 'Change the action done when the clock is clicked' 
3. Click on the dropdown menu
4. Select an option to test out
5. (Optional Possibly) Restart ElevenClock (I tried with and without restarting and it didn't work for me)
8. See error by clicking on the ElevenClock

## Expected behaviour
Selecting the Elevenclock should preform the action you selected instead of opening calendar.

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.5.0 (v3.5) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2256, 1504)
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1919, 1434, 300, 69)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2256, 1504)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:False, legacyFullScreenMethod:False
can't parse 
🟡 Desktop button enabled
🔵 Restart loop: 1
🟣 Expected AttributeError on backgroundLoop thread
🟢 Loaded clocks in 4.287497043609619
🟣 Expected AttributeError on backgroundLoop thread
🟢 Cached text input host hwnd: 11207224
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟡 System tray icon disabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to True
🟢 Loaded everything in 9.078349113464355
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 512, in wrap_socket

🔴   File "ssl.py", line 1070, in _create

🔴   File "ssl.py", line 1341, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 127, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>)
🔵 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 512, in wrap_socket

🔴   File "ssl.py", line 1070, in _create

🔴   File "ssl.py", line 1341, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 127, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>)
🔵 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/warnsign.png
🔵 Copying log to the clipboard...

```

**Comment by martinet101** [comment]
> * [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**

Can you please try that?
