### ISSUE TITLE
[BUG/ISSUE] ElevenClock generates lot of data in Temp folder (10GB in 5 months !)

### ISSUE THREAD

**Issue by theblackhole** [martinet101/ElevenClock#790]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
ElevenClock generates a lot of `_MEIxxxxx` folders in `%localappdata%\Temp`, each one is about 100Mo.
Since I installed ElevenClock in January, I've accumulated **10GB** of those `_MEIxxxxx` folders in my temp directory (**!**)

## To Reproduce
Use ElevenClock for a certain period of time

## Expected behaviour
If it is related to automatic updates, it should be automatically cleaned after installation (except the logs maybe and perhaps the last 1 or 2 versions)

## Screenshots
![image](https://user-images.githubusercontent.com/7818904/170785853-b851db6c-5f0e-4b28-9b8b-46a80a0e0f44.png)

## The Log

I don't think it is required here but I'll happily provide it if needed.

**Comment by martinet101** [comment]
Windows should remove those files...

Anyway, i'll try to fix that

**Comment by martinet101** [comment]
You can no update to the fixed version

**Comment by theblackhole** [comment]
Sorry, it looks like the cleaning process has issues, no `_MEI*` folders are cleaned in tmp.
Fortunately I might have a lead that could help you: WizTree recorded something: a `_MEI*` dir has been created today then cleared at the root of my `C:\` drive. 

![image](https://user-images.githubusercontent.com/7818904/177408751-c8c9d0b5-f341-49dd-9858-d8c1d7553233.png)

After a restart of ElevenClock, another one has been created (`_MEI17962`).

Logs:
```
It took 0.00099945068359375 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.6.1 (v3.61) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "fr"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Clock on the bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1924, 1034, 200, 46)
🔵 Font families   : []
🔵 Custom font     : Segoe UI Variable Small Semibol
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 0, 1920, 1080)
🟢 Clock on the bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-1916, 1034, 200, 46)
🔵 Font families   : []
🔵 Custom font     : Segoe UI Variable Small Semibol
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🟢 Loaded clocks in 2.4331166744232178
🔵 Restart loop: 1
None
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
None
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 3.584486484527588
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 244, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Accès refusé: 'C:\\_MEI111882\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Accès refusé: 'C:\\_MEI111882\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 244, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Accès refusé: 'C:\\_MEI17962\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Accès refusé: 'C:\\_MEI17962\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 513, in wrap_socket

🔴   File "ssl.py", line 1071, in _create

🔴   File "ssl.py", line 1342, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 128, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>)
🔵 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 513, in wrap_socket

🔴   File "ssl.py", line 1071, in _create

🔴   File "ssl.py", line 1342, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 128, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>)
🔵 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://upload.wikimedia.org/wikipedia/commons/d/db/Google_Translate_Icon.png
🔵 Copying log to the clipboard...
```

**Comment by martinet101** [comment]
Yes, it is half-broken (and I have spotted why). I was planning to get that fix today or tomorrow if i can

**Comment by martinet101** [comment]
Please update, this should be fixed

**Comment by theblackhole** [comment]
Perfect, +15GB of free space after the 3.6.2 update with only one `_MEI` folder left at the root and one in `Temp` 👌 

Here's a coffee, you deserve it: [☕](https://Ko-fi.com/home/coffeeshop?txid=d98d653f-fe8e-420a-91e6-63ff39b3fdae&mode=public&img=ogiboughtsomeone)

**Comment by martinet101** [comment]
> Here's a coffee, you deserve it: [☕](https://Ko-fi.com/home/coffeeshop?txid=d98d653f-fe8e-420a-91e6-63ff39b3fdae&mode=public&img=ogiboughtsomeone)

Wow thank youy ;)





> only one `_MEI` folder left at the root

The one at the root can (or at least should) be removed safely without affecting ElevenClock
