### ISSUE TITLE
[ISSUE] HTTP Error 308: Permanent Redirect

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [martinet101/ElevenClock#847]
## Describe the bug
HTTP Error 308 occurs for the notification display on the setting screen.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'ElevenClock Settings'
2. See error

## Expected behaviour
Notification from the author should be displayed.

## Screenshots
![image](https://user-images.githubusercontent.com/11265280/181409995-a1e4cfb8-3bcd-475a-b6fe-a3ffccb5fb27.png)

## The Log
It took 0.0 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.6.4 (v3.64) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "ja"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 3840, 2160)
🟢 Clock on the bottom
🔵 Restart loop: 1
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3483, 2080, 350, 80)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %#H:%M:%S
%Y/%m/%d
🔵 Full screen rect:  (0, 0, 3840, 2160)
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🟣 Expected AttributeError on backgroundLoop thread
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(3840, 0, 3840, 2160)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(7323, 2080, 350, 80)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %#H:%M:%S
%Y/%m/%d
🔵 Full screen rect:  (3840, 0, 7680, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🟡 Desktop button enabled
🟢 Loaded clocks in 5.992968797683716
🟢 Cached text input host hwnd: 4527224
None
None
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 7.3305768966674805
🟢 Green lignt to rease temp dirs
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 248, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] アクセスが拒否されました。: 'C:\\Users\\新宅伸啓\\AppData\\Local\\Temp\\_MEI514002\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] アクセスが拒否されました。: 'C:\\Users\\新宅伸啓\\AppData\\Local\\Temp\\_MEI514002\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 248, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] アクセスが拒否されました。: 'C:\\Users\\新宅伸啓\\AppData\\Local\\Temp\\_MEI514722\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] アクセスが拒否されました。: 'C:\\Users\\新宅伸啓\\AppData\\Local\\Temp\\_MEI514722\\libcrypto-1_1.dll')
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: yyyy'年'M'月'd'日'
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2922, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 308: Permanent Redirect)
🔵 Showing tooltip
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Showing tooltip
🔵 Long date string: yyyy'年'M'月'd'日'
🟡 Custom loaded date time format: %#H:%M:%S
%Y/%m/%d
🟡 Closing clock on {'Monitor': (0, 0, 3840, 2160), 'Work': (0, 0, 3840, 2076), 'Flags': 1, 'Device': '\\\\.\\DISPLAY2'}
🟡 Closing clock on {'Monitor': (3840, 0, 7680, 2160), 'Work': (3840, 0, 7680, 2076), 'Flags': 0, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 3840, 2160)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3483, 2080, 350, 80)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %#H:%M:%S
%Y/%m/%d
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(3840, 0, 3840, 2160)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(7323, 2080, 350, 80)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %#H:%M:%S
%Y/%m/%d
🔵 Full screen rect:  (3840, 0, 7680, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Cached text input host hwnd: 4527224
🟡 Desktop button enabled
🟡 Custom loaded date time format: %#H:%M:%S
%Y/%m/%d
🔵 Restart loop: 1
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2922, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 308: Permanent Redirect)
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Copying log to the clipboard...

**Comment by martinet101** [comment]
Yes, this will be fixed soon

**Comment by martinet101** [comment]
Fixed!
