### ISSUE TITLE
[BUG] error messages after monitors have been turned off due to inactivity

### ISSUE THREAD

**Issue by walnuts84** [martinet101/ElevenClock#854]
## Describe the bug
After I have been away from my computer for a while, and it has turned off the monitors due to inactivity, I see a bunch of errors when coming back. I have noticed that the longer time I have been away, the more error messages there is. 

Error Messages: 
- Message 1
Fatal error detected
Error loading Python DLL 'C:\Users\username\AppData\Local\Temp\_MEI42282\python310.dll'.
LoadLibrary: The specified module could not be found. 

- Message 2
Fatal error detected
Failed to extract tcl\msgs\ru.msg: failed to open target file!
fopen: No such file or directory

## To Reproduce
Steps to reproduce the behaviour:
1. ensure ElevenClock is started
2. In windows settings: System > Power > Screen and Sleep, ensure that "When plugged in, turn off my screen after:" is set to eg. "5 minutes" and that Power mode is set to Best Performance
3. Do not use the computer for approx 10-15 minutes
4. See error messages appear when starting to use computer

## Expected behaviour
I expect that 0 error messages is visible after returning to pc after a coffee break.

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 657, in loadLangFile

🔴   File ".\tools.py", line 657, in loadLangFile

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/holen/AppData/Local/Temp/_MEI16602/resources/../lang/lang_nb.json'

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/holen/AppData/Local/Temp/_MEI16602/resources/../lang/lang_nb.json'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:/Users/holen/AppData/Local/Temp/_MEI16602/resources/../lang/lang_nb.json')
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 657, in loadLangFile

🔴   File ".\tools.py", line 657, in loadLangFile

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/holen/AppData/Local/Temp/_MEI16602/resources/../lang/lang_en.json'

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/holen/AppData/Local/Temp/_MEI16602/resources/../lang/lang_en.json'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:/Users/holen/AppData/Local/Temp/_MEI16602/resources/../lang/lang_en.json')
It took 0.0010035037994384766 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.7.0 (v3.7) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "nb"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3636, 1034, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d.%m.%Y
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
can't parse ""
🟢 Loaded clocks in 1.1355834007263184
🔵 Restart loop: 1
None
None
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to True. DisableNotifications is set to False
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 126, in updateIfPossible

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 126, in updateIfPossible

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\holen\AppData\Local\Temp\embedded.hvyw06bg.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "C:\Users\holen\AppData\Local\Temp\embedded.hvyw06bg.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI16602\\base_library.zip'

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI16602\\base_library.zip'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI16602\\base_library.zip')
🟢 Loaded everything in 2.3391025066375732
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d.%m.%Y
🟢 Green lignt to rease temp dirs
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI218682\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI218682\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI236842\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI236842\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI243562\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI243562\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI245362\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI245362\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI33282\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI33282\\libcrypto-1_1.dll')
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 126, in updateIfPossible

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\holen\AppData\Local\Temp\embedded.hvyw06bg.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI16602\\base_library.zip'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI16602\\base_library.zip')
🟡 Closing clock on {'Monitor': (1920, 0, 3840, 1080), 'Work': (1920, 0, 3840, 1032), 'Flags': 0, 'Device': '\\\\.\\DISPLAY1'}
🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3636, 1034, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d.%m.%Y
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d.%m.%Y
🟡 Closing clock on {'Monitor': (1920, 0, 3840, 1080), 'Work': (1920, 0, 3840, 1032), 'Flags': 0, 'Device': '\\\\.\\DISPLAY1'}
🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3636, 1034, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d.%m.%Y
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: dd.MM.yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d.%m.%Y
🔵 Restart loop: 2
🔵 Restart loop: 1
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1447, in connect

🔴   File "http\client.py", line 941, in connect

🔴   File "socket.py", line 824, in create_connection

🔴   File "socket.py", line 955, in getaddrinfo

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\holen\AppData\Local\Temp\embedded.hvyw06bg.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI16602\\base_library.zip'

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2928, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI16602\\base_library.zip'>

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 941, in connect

🔴   File "socket.py", line 824, in create_connection

🔴   File "socket.py", line 955, in getaddrinfo

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\holen\AppData\Local\Temp\embedded.hvyw06bg.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI16602\\base_library.zip'

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2928, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1377, in http_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI16602\\base_library.zip'>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [Errno 2] No such file or directory: 'C:\\Users\\holen\\AppData\\Local\\Temp\\_MEI16602\\base_library.zip'>)

**Comment by martinet101** [comment]
Can you please enable this? 
![image](https://user-images.githubusercontent.com/53119851/182249269-b8dc02e7-a376-46dc-bf8e-8f3a89c3a7cc.png)

**Comment by ForthtuN** [comment]
I have it enabled, and it still popups 3 errors (1 for each of the screen maybe since i haved 3 monitors?) after going into turn off mode when inactive. The error messages are empty without any text

**Comment by martinet101** [comment]
Can you please send a screenshot of the error?

**Comment by ForthtuN** [comment]
![fatal error](https://user-images.githubusercontent.com/10890970/182960289-781148e6-2afd-4281-9e98-fe090fd2eaed.jpg)

Timing was perfect when i got back to the pc haha

It just says Fatal error without any error information, just empty

**Comment by martinet101** [comment]
Do you have any third - party anti-virus?


Can you please fully uninstall and reinstall ElevenClock?

**Comment by ForthtuN** [comment]
> Do you have any third - party anti-virus?
> 
> Can you please fully uninstall and reinstall ElevenClock?

Nope, im not using any strange things, just a normal gaming computer with no strange softwares and no VR or third party Antivirus or performance/cleanup tools. 

I did as you said and it stills shows up after reinstall after the screen been off (Using 3 screens, two of them connected to CPU/Motherboard GPU and 1 connected to main GPU RTX 3080)

**Comment by martinet101** [comment]
Do you think it could be related to #870?

**Comment by martinet101** [comment]
The error should be now fixed, please stay tuned for the next update!

**Comment by ForthtuN** [comment]
> The error should be now fixed, please stay tuned for the next update!

Hi again. Im sorry to say that it seems to have been getting worse. Im now having more errors than ever i think. 
I post screenshot of it
![worsethanever](https://user-images.githubusercontent.com/10890970/191887778-a61d66a7-bdc8-429d-9fe0-d9e5dc88205f.jpg)
