### ISSUE TITLE
[BUG/ISSUE] Show clock when taskbar set to hide automatically not working

### ISSUE THREAD

**Issue by hughmathimati** [martinet101/ElevenClock#858]
## Describe the bug
When the option "Show the clock when the taskbar is set to hide automatically" is enabled, the clock still doesn't show. This might already have a simple solution but I searched up "elevenclock not showing" and the only solution I could get to work was to downgrade to 2.5, which did work when I tried it but seemed to have blurrier text or something? For some reason 3.6 and 3.5 auto-update to 3.7 even after turning auto-update and check for updates off in the settings before running the installer.
## To Reproduce
Steps to reproduce the behaviour:
I have my taskbar set to automatically hide.
It might just be my PC, but after installing ElevenClock, even if I select the show over fullscreen option in the welcome config and "Show the clock even when the taskbar is set to hide automatically" option, the clock still only shows when I move my mouse to the bottom of my screen. I have tried installing from both the Microsoft store and Github, and I have tried deleting the ".elevenclock" folder. It happens with the "show on primary screen" option both on and off, and it happens in both versions 3.7 and 3.6.4. Ever since the problem started happening, I have restarted my PC and it hasn't helped.

## Expected behaviour
Previously, the clock would show at all times even with the taskbar down.

## Screenshots:
![image](https://user-images.githubusercontent.com/102939561/182447753-0d459950-bc4b-4548-bd64-edaf09e61dad.png)

## The Log

```
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 186, in setSettingsValue

🔴   File ".\tools.py", line 186, in setSettingsValue

🔴   File ".\globals.py", line 15, in loadTimeFormat

🔴   File ".\globals.py", line 15, in loadTimeFormat

🔴 NotImplementedError: loadTimeFormat function has not been defined!

🔴 NotImplementedError: loadTimeFormat function has not been defined!

🔴 Note this traceback was caught by reporter and has been added to the log (loadTimeFormat function has not been defined!)
It took 0.0 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.7.0 (v3.7) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟡 This is the primary screen and is set to be skipped
🟢 Loaded clocks in 0.42102885246276855
🔵 Restart loop: 1
None
None
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🟡 This is the primary screen and is set to be skipped
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🟡 This is the primary screen and is set to be skipped
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2356, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Restart loop: 3
🟢 Default settings loaded
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🟡 Closing clock on {'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2560, 1440), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2356, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🟢 Loaded everything in 1.6116747856140137
🟢 Green lignt to rease temp dirs
🟢 Cached text input host hwnd: 197210
🔵 Restart loop: 3
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Restart loop: 2
🔵 Restart loop: 1
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🟡 Closing clock on {'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2560, 1440), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2356, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🟢 Cached text input host hwnd: 197210
🔵 Restart loop: 1
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🟡 Closing clock on {'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2560, 1440), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2356, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🟡 Closing clock on {'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2560, 1440), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2356, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🟢 Cached text input host hwnd: 197210
🔵 Restart loop: 2
🔵 Restart loop: 1
🔵 Announcement URL: https://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://images.vexels.com/media/users/3/128603/isolated/lists/c3baedd2e3624a2ed60434ab856cea3d-plantilla-de-venta-de-burbuja-roja.png
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🟡 Closing clock on {'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2560, 1440), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2356, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🟢 Cached text input host hwnd: 197210
🔵 Restart loop: 1
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🟡 Closing clock on {'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2560, 1440), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2356, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%A
%#m/%#d/%Y
🟢 Cached text input host hwnd: 197210
🔵 Restart loop: 1
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🟡 Closing clock on {'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2560, 1440), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2356, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🟢 Cached text input host hwnd: 197210
🔵 Restart loop: 1
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🟡 Closing clock on {'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2560, 1440), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2356, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🟢 Cached text input host hwnd: 197210
🔵 Restart loop: 1
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🟡 Closing clock on {'Monitor': (0, 0, 2560, 1440), 'Work': (0, 0, 2560, 1440), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🟡 This is the primary screen and is set to be skipped
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🔵 Restart loop: 1
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2356, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%A
%#m/%#d/%Y
🟢 Cached text input host hwnd: 197210
🔵 Restart loop: 1
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
```

## Additional context
1. Is there a way for me to downgrade to 3.6 or 3.5 without it auto-updating? I can try these versions to see if it works then
2. Do I really have to just run version 2.5?

**Comment by martinet101** [comment]
If you disable updates you should be able to install versions 3.5 and 3.6. Have you tried disabling updates on version 2.5 and then installing 3.5?

**Comment by martinet101** [comment]
For me the updates disabling works fine, tested just right now

**Comment by martinet101** [comment]
Indeed the option does not work. This needs to be fixed!

**Comment by hughmathimati** [comment]
I installed 2.5 and unchecked auto-check for updates and auto-install updates.
![image](https://user-images.githubusercontent.com/102939561/182472357-7062b770-7bce-4511-a2aa-9bd816e961d1.png)
After running the 3.5 installer, my mouse gets a blue circle for a second or two, during which I cannot open ElevenClock settings. Afterwards, I open ElevenClock settings and check the version and it's 3.7.0.
![image](https://user-images.githubusercontent.com/102939561/182472907-365529a4-c48e-4546-ac9a-0daee368270d.png)
When I tried 3.4.1 and 3.6, the same thing happens. What else do I need to do to be able to successfully downgrade?

**Comment by martinet101** [comment]
Weird... 

Can you check the .elevenclock folder for a file called like this?
![image](https://user-images.githubusercontent.com/53119851/182473493-344c4975-7c3e-4ffc-b1e2-1016167c81c2.png)


If it is not there, can you please create it?

**Comment by hughmathimati** [comment]
The file is there. Not sure what I'm supposed to do with it though.
![image](https://user-images.githubusercontent.com/102939561/182492813-1d9d9568-b28a-40fe-a4af-8de0814def61.png)
Maybe the Updated3.7.0Already file has something to do with it but idk.

**Comment by martinet101** [comment]
> Maybe the Updated3.7.0Already file has something to do with it but idk

No, if the file is there it shouldn't autoupdate

**Comment by martinet101** [comment]
Fixed!
