### ISSUE TITLE
[BUG/ISSUE] Alignment issue, overlap using custom format

### ISSUE THREAD

**Issue by tjorim** [martinet101/ElevenClock#867]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
After using a custom date/time format on the latest version, the alignment seems off.

## To Reproduce
Set a custom format, for example:
%d/%m/%Y
%H:%M:%S
%y%W.%u
Also when resetting everything, the issue appears after setting this.

## Expected behaviour
No overlap with other UI elements.

## Screenshots
<img width="170" alt="image" src="https://user-images.githubusercontent.com/1294876/183089882-d45d7be9-d893-4caa-8a48-bd2f1ea76401.png">

## The Log

```
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 186, in setSettingsValue

🔴   File ".\tools.py", line 186, in setSettingsValue

🔴   File ".\globals.py", line 15, in loadTimeFormat

🔴   File ".\globals.py", line 15, in loadTimeFormat

🔴 NotImplementedError: loadTimeFormat function has not been defined!

🔴 NotImplementedError: loadTimeFormat function has not been defined!

🔴 Note this traceback was caught by reporter and has been added to the log (loadTimeFormat function has not been defined!)
It took 0.009974002838134766 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.7.1 (v3.71) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "nl"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟡 This is the primary screen and is set to be skipped
🟢 Loaded clocks in 2.576094627380371
🔵 Restart loop: 1
None
None
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🟡 This is the primary screen and is set to be skipped
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🟡 This is the primary screen and is set to be skipped
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1614, 1011, 300, 69)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🟢 Default settings loaded
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1008), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1614, 1011, 300, 69)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🟢 Cached text input host hwnd: 131680
🔵 Restart loop: 4
🟢 Cached text input host hwnd: 131680
🔵 Restart loop: 3
🟢 Loaded everything in 5.871330976486206
🟢 Green lignt to rease temp dirs
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 614, in _rmtree_unsafe

🔴   File "shutil.py", line 614, in _rmtree_unsafe

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI170323\\tcl\\msgs\\es_uy.msg'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 2] The system cannot find the file specified: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI170323\\tcl\\msgs\\es_uy.msg')
🔵 Restart loop: 2
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 513, in wrap_socket

🔴   File "ssl.py", line 1071, in _create

🔴   File "ssl.py", line 1342, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 130, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>)
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 513, in wrap_socket

🔴   File "ssl.py", line 1071, in _create

🔴   File "ssl.py", line 1342, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 130, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 133, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 308: Permanent Redirect)
🔵 Announcement URL: https://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://images.vexels.com/media/users/3/128603/isolated/lists/c3baedd2e3624a2ed60434ab856cea3d-plantilla-de-venta-de-burbuja-roja.png
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1008), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1614, 1011, 300, 69)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M
%#d/%m/%Y
🟢 Cached text input host hwnd: 131680
🔵 Restart loop: 1
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1008), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1614, 1011, 300, 69)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🟢 Cached text input host hwnd: 131680
🔵 Restart loop: 1
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1008), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(6, 1011, 300, 69)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟠 Clock is cover!!!
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock cover geometry: PySide2.QtCore.QRect(1614, 1011, 300, 69)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:True, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🟢 Cached text input host hwnd: 131680
🟢 Cached text input host hwnd: 131680
🔵 Restart loop: 1
🔵 Starting update check
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1008), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1008), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1008), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1614, 1011, 300, 69)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🟢 Cached text input host hwnd: 131680
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 513, in wrap_socket

🔴   File "ssl.py", line 1071, in _create

🔴   File "ssl.py", line 1342, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 130, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>)
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 513, in wrap_socket

🔴   File "ssl.py", line 1071, in _create

🔴   File "ssl.py", line 1342, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 130, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 133, in updateIfPossible

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 308: Permanent Redirect)
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
```

Also noticed FileNotFoundError once again.
The settings reset disabled the 'experimental solution'.
Is this still needed to be an optional thing?

**Comment by martinet101** [comment]
> Is this still needed to be an optional thing?

I would recommend leaving it enabled.

----------------------------------

About the misalignment, this is not an _issue_ but rather a thing you'll have to fix by specifying position offsets
![image](https://user-images.githubusercontent.com/53119851/183240331-cc7252b5-b7c0-46f3-b6e4-a4e8c37b5483.png)
