### ISSUE TITLE
[BUG/ISSUE] Failed to obtain/convert traceback!

### ISSUE THREAD

**Issue by tjorim** [martinet101/ElevenClock#868]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
Similar error as before: Failed to obtain/convert traceback!

## To Reproduce
Unplugged HumanScale, got errors.

## Expected behaviour
No errors, and no need to enable the experimental function.

## Screenshots
<img width="630" alt="image" src="https://user-images.githubusercontent.com/1294876/183125953-b8350492-dfb4-4635-8bb0-67485bbd7a08.png">

## The Log

```
It took 0.005983829498291016 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.7.1 (v3.71) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "nl"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🔵 Restart loop: 1
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1614, 1011, 300, 69)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🟡 Desktop button enabled
🟣 Expected AttributeError on backgroundLoop thread
🟢 Loaded clocks in 15.104211568832397
🟢 Cached text input host hwnd: 131680
None
🟣 Expected AttributeError on backgroundLoop thread
None
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 126, in updateIfPossible

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 126, in updateIfPossible

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\jtielema\AppData\Local\Temp\embedded._9frfnw1.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "C:\Users\jtielema\AppData\Local\Temp\embedded._9frfnw1.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI222682\\base_library.zip'

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI222682\\base_library.zip'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI222682\\base_library.zip')
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 17.987539529800415
🟢 Green lignt to rease temp dirs
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI214642\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI214642\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI256482\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI256482\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI262042\\libffi-7.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI262042\\libffi-7.dll')
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1008), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1614, 1011, 300, 69)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🟢 Cached text input host hwnd: 131680
🔵 Restart loop: 1
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1447, in connect

🔴   File "http\client.py", line 941, in connect

🔴   File "socket.py", line 824, in create_connection

🔴   File "socket.py", line 955, in getaddrinfo

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\jtielema\AppData\Local\Temp\embedded._9frfnw1.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI222682\\base_library.zip'

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2930, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI222682\\base_library.zip'>

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 941, in connect

🔴   File "socket.py", line 824, in create_connection

🔴   File "socket.py", line 955, in getaddrinfo

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\jtielema\AppData\Local\Temp\embedded._9frfnw1.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI222682\\base_library.zip'

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2930, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1377, in http_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI222682\\base_library.zip'>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI222682\\base_library.zip'>)
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 126, in updateIfPossible

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\jtielema\AppData\Local\Temp\embedded._9frfnw1.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI222682\\base_library.zip'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI222682\\base_library.zip')
🔵 Copying log to the clipboard...

```

**Comment by tjorim** [comment]
I enabled the 'fix' again and will keep an eye on it.

**Comment by tjorim** [comment]
Seems to be fixed by enabling the 'FileNotFoundError experimental solution' again.
Any plans to make this setting default or is it not a proper solution?
We will be rolling out ElevenClock to a few computers in our organization and not having users manually enable it would be easier I think.

**Comment by martinet101** [comment]
Hi, the bug is still under study, and this is a temporary fix.

However, if you want to enable it by default, you can always deploy ElevenClock with a script that creates a .elevenclock folder in the user's directory and creates an empty file called `DisableDirRemovingThread`. A CMD approach could be

```cmd
ElevenClock.Installer.exe /unattended /verysilent
cd %userprofile%
mkdir .elevenclock
cd .elevenclock
call>DisableDirRemovingThread
```

**Comment by martinet101** [comment]
Hi @tjorim, i have implemented a new fix that should do the job.

On the next update, please disable the `Avoid FileNotFoundError` option and give it a shot!
