### ISSUE TITLE
[BUG] (on latest version 3.7.1, every time my laptop wakes from sleep I have an error message, attached below)

### ISSUE THREAD

**Issue by nicky007** [martinet101/ElevenClock#870]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ ] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
on latest version 3.7.1, every time my laptop wakes from sleep I have an error message:
The error message is displayed on a new tab on the browser.
Link:
https://www.somepythonthings.tk/error-report/?appName=ElevenClock&errorBody={s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}OS:{s}Windows{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}Version:{s}(%2710%27,{s}%2710.0.22000%27,{s}%27SP0%27,{s}%27Multiprocessor{s}Free%27){l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}OS{s}Architecture:{s}AMD64{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}APP{s}Architecture:{s}64bit{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}APP{s}Version:{s}Unknown{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}APP{s}Version{s}Code:{s}Unknown{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}Program:{s}ElevenClock{l}{l}-----------------------------------------------------------------------------------------{l}{l}{l}{l}ElevenClock%20Log:{l}{l}{l}{l}{l}Traceback{s}(most{s}recent{s}call{s}last):{l}{s}{s}File{s}%22\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py%22,{s}line{s}4,{s}in{s}%3Cmodule%3E{l}{s}{s}File{s}%22PyInstaller\loader\pyimod03_importers.py%22,{s}line{s}495,{s}in{s}exec_module{l}{s}{s}File{s}%22ctypes\__init__.py%22,{s}line{s}8,{s}in{s}%3Cmodule%3E{l}{l}ImportError:{s}DLL{s}load{s}failed{s}while{s}importing{s}_ctypes:{s}The{s}specified{s}module{s}could{s}not{s}be{s}found.%3Cclass{s}%27ImportError%27%3E:{s}DLL{s}load{s}failed{s}while{s}importing{s}_ctypes:{s}The{s}specified{s}module{s}could{s}not{s}be{s}found.

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

## Additional context
![2022-08-07 09_40_29-SomePythonThings - Error Report](https://user-images.githubusercontent.com/5091058/183301725-5483e762-e4fa-4296-ac14-af084438faf6.png)

**Comment by cache117** [comment]
I'm having what appears to be the same issue, so instead of creating a new issue, I'll post the Log that I have, in case it's helpful.

## The Log

```
It took 0.0 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.7.1 (v3.71) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1716, 1034, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using black text (light mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 Restart loop: 1
🟣 Expected AttributeError on backgroundLoop thread
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 409, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-254, 1431, 250, 58)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using black text (light mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🔵 Full screen rect:  (-1920, 409, 0, 1489)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🟡 Desktop button enabled
🟢 Loaded clocks in 1.757997751235962
None
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
None
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟣 Expected AttributeError on backgroundLoop thread
🟢 Cached text input host hwnd: 1449064
🟣 Expected AttributeError on backgroundLoop thread
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🔵 System tray icon enabled
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 Starting update check
🟠 Can't remove lock file, file exist status: False
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 3.3649959564208984
🟢 Green lignt to rease temp dirs
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI435842\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI435842\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI79882\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI79882\\libcrypto-1_1.dll')
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1930, 399, 10, 1499) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1930, 399, 10, 1499) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1438) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1438) Fullscreen rect: (-1920, 409, 0, 1489)
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: https://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://images.vexels.com/media/users/3/128603/isolated/lists/c3baedd2e3624a2ed60434ab856cea3d-plantilla-de-venta-de-burbuja-roja.png
🔵 Saving log...
```

I get other errors sometimes, but they mostly seem to be related to that `Access is denied` error.

**Comment by loekf** [comment]
Checking is this the same bug/error I'm seeing when my laptop returns from sleep mode ?
![Screenshot 2022-08-17 080705](https://user-images.githubusercontent.com/35070301/185046602-b400dff9-6f88-4804-ace5-c36262783ac4.png)

**Comment by martinet101** [comment]
Yes, it possibly is

**Comment by cache117** [comment]
The error that loekf posted is one of the same error I'm getting when my laptop wakes from sleep. 

Here's another log from this morning with a lot more errors:
```
It took 0.0 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.7.1 (v3.71) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1716, 1034, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using black text (light mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🔵 Restart loop: 1
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
can't parse ""
🟡 Desktop button enabled
🟣 Expected AttributeError on backgroundLoop thread
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 409, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-254, 1431, 250, 58)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using black text (light mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🔵 Full screen rect:  (-1920, 409, 0, 1489)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🟡 Desktop button enabled
🟢 Loaded clocks in 3.721997022628784
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1930, 399, 10, 1499) Fullscreen rect: (-1920, 409, 0, 1489)
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟢 Cached text input host hwnd: 1320036
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
None
🟡 Fullscreen window detected! (-1930, 399, 10, 1499) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
🟡 Fullscreen window detected! (-1929, 400, 9, 1498) Fullscreen rect: (-1920, 409, 0, 1489)
None
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🟠 Can't remove lock file, file exist status: False
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 126, in updateIfPossible

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\cache\AppData\Local\Temp\embedded.6gp4s_am.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI75602\\base_library.zip'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI75602\\base_library.zip')
🟢 Loaded everything in 16.217984676361084
🟢 Green lignt to rease temp dirs
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 614, in _rmtree_unsafe

🔴   File "shutil.py", line 623, in _rmtree_unsafe

🔴   File "shutil.py", line 621, in _rmtree_unsafe

🔴 FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI134802\\resources'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 2] The system cannot find the file specified: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI134802\\resources')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI236842\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI236842\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI297562\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI297562\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI341202\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI341202\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI352322\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI352322\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI377122\\pyexpat.pyd'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI377122\\pyexpat.pyd')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI458362\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI458362\\libcrypto-1_1.dll')
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI470442\\python310.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Access is denied: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI470442\\python310.dll')
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 126, in updateIfPossible

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\cache\AppData\Local\Temp\embedded.6gp4s_am.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI75602\\base_library.zip'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI75602\\base_library.zip')
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1447, in connect

🔴   File "http\client.py", line 941, in connect

🔴   File "socket.py", line 824, in create_connection

🔴   File "socket.py", line 955, in getaddrinfo

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\cache\AppData\Local\Temp\embedded.6gp4s_am.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI75602\\base_library.zip'

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2930, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI75602\\base_library.zip'>

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 941, in connect

🔴   File "socket.py", line 824, in create_connection

🔴   File "socket.py", line 955, in getaddrinfo

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\cache\AppData\Local\Temp\embedded.6gp4s_am.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI75602\\base_library.zip'

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2930, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1377, in http_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI75602\\base_library.zip'>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [Errno 2] No such file or directory: 'C:\\Users\\cache\\AppData\\Local\\Temp\\_MEI75602\\base_library.zip'>)
🔵 Saving log...
```
Also, the one from the error report:
```
                        OS: Windows
                   Version: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: 3.7.1
          APP Version Code: 3.71
                   Program: ElevenClock

-----------------------------------------------------------------------------------------



ElevenClock Log:




Traceback (most recent call last):
  File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 38, in <module>

ModuleNotFoundError: No module named 'PySide2.QtGui'<class 'ModuleNotFoundError'>: No module named 'PySide2.QtGui'
```

**Comment by martinet101** [comment]
The error should be fixed, please stay tuned for the next version!
