### ISSUE TITLE
[BUG] FileNotFoundError on v3.7.3

### ISSUE THREAD

**Issue by tjorim** [martinet101/ElevenClock#899]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
On version 3.7.3, but still getting File Not Found Error

## To Reproduce
Steps to reproduce the behaviour:
1. Wait some time
2. It happens
3. Sometimes random
4. Sometimes after waking from sleep
5. Sometimes after connecting to external screen

## Expected behaviour
See screenshots below

## Screenshots
![image](https://user-images.githubusercontent.com/1294876/188491718-b217a4ba-ed2c-413c-8fc7-15eacf14ca56.png)

## The Log

```
It took 0.007970094680786133 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.7.3 (v3.73) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "nl"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🔵 Restart loop: 1
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1620, 1011, 300, 69)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
can't parse ""
🟡 Desktop button enabled
🟣 Expected AttributeError on backgroundLoop thread
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, -114, 3840, 1200)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(5560, 1041, 200, 45)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🔵 Full screen rect:  (1920, -114, 5760, 1086)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🟡 Desktop button enabled
🔵 Initializing clock 2...
🔵 Using taskbar background color
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1916, -1314, 3840, 1200)
🟢 Clock on the bottom
🟢 Clock on the right
🟡 Fullscreen window detected! (0, 0, 1920, 1080) Fullscreen rect: (0, 0, 1920, 1080)
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(5556, -159, 200, 45)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %d/%m/%Y
%H:%M:%S
%y%W.%u
🔵 Full screen rect:  (1916, -1314, 5756, -114)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🟡 Desktop button enabled
🟢 Loaded clocks in 30.0742404460907
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
None
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
None
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟡 Fullscreen window detected! (0, 0, 1920, 1080) Fullscreen rect: (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 126, in updateIfPossible

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 126, in updateIfPossible

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\jtielema\AppData\Local\Temp\embedded.p95g7h2j.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "C:\Users\jtielema\AppData\Local\Temp\embedded.p95g7h2j.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI24362\\base_library.zip'

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI24362\\base_library.zip'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI24362\\base_library.zip')
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 39.669353008270264
🟢 Green lignt to rease temp dirs
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 246, in clearTmpDir

🔴 FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI143602' -> 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_OLDMEI143602'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI143602' -> 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_OLDMEI143602')
🟡 Fullscreen window detected! (0, 0, 1920, 1080) Fullscreen rect: (0, 0, 1920, 1080)
🟡 Fullscreen window detected! (0, 0, 1920, 1080) Fullscreen rect: (0, 0, 1920, 1080)
🟡 Fullscreen window detected! (0, 0, 1920, 1080) Fullscreen rect: (0, 0, 1920, 1080)
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 1447, in connect

🔴   File "http\client.py", line 941, in connect

🔴   File "socket.py", line 824, in create_connection

🔴   File "socket.py", line 955, in getaddrinfo

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\jtielema\AppData\Local\Temp\embedded.p95g7h2j.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI24362\\base_library.zip'

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2930, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1391, in https_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI24362\\base_library.zip'>

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1282, in request

🔴   File "http\client.py", line 1328, in _send_request

🔴   File "http\client.py", line 1277, in endheaders

🔴   File "http\client.py", line 1037, in _send_output

🔴   File "http\client.py", line 975, in send

🔴   File "http\client.py", line 941, in connect

🔴   File "socket.py", line 824, in create_connection

🔴   File "socket.py", line 955, in getaddrinfo

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\jtielema\AppData\Local\Temp\embedded.p95g7h2j.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI24362\\base_library.zip'

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2930, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1377, in http_open

🔴   File "urllib\request.py", line 1351, in do_open

🔴 urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI24362\\base_library.zip'>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI24362\\base_library.zip'>)
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 126, in updateIfPossible

🔴   File "encodings\__init__.py", line 99, in search_function

🔴   File "C:\Users\jtielema\AppData\Local\Temp\embedded.p95g7h2j.zip\shibokensupport\__feature__.py", line 142, in _import

🔴   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

🔴   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked

🔴   File "<frozen importlib._bootstrap>", line 945, in _find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec

🔴   File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec

🔴   File "<frozen zipimport>", line 170, in find_spec

🔴   File "<frozen importlib._bootstrap>", line 431, in spec_from_loader

🔴   File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location

🔴   File "<frozen zipimport>", line 229, in get_filename

🔴   File "<frozen zipimport>", line 752, in _get_module_code

🔴   File "<frozen zipimport>", line 586, in _get_data

🔴 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI24362\\base_library.zip'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 2] No such file or directory: 'C:\\Users\\jtielema\\AppData\\Local\\Temp\\_MEI24362\\base_library.zip')
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
```

**Comment by martinet101** [comment]
Ok, i'll try to solve it again. For me, the way it happened now works just fine.

Please keep the prevent error option until i can get this fixed

**Comment by martinet101** [comment]
Could you please test out this version please?

https://drive.google.com/file/d/1-lIfomRcVepQJLaQ97qwDPVB9yJDn8wZ/view?usp=sharing

**Comment by tjorim** [comment]
It's running fine the first day. Not always reproducible so will keep it running for a while.

**Comment by martinet101** [comment]
You can now update to the stable release of the beta version i sent. 

Version 3.8.0 won't crash anymore since there won't be anymore temp folder conflicting since ElevenClock is now distributed as a multi-file executable (thanks to the upgrade to Qt6)
